apiVersion: v1
kind: PersistentVolume
metadata:
  name: datagov-dags-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /dags